all: java.policy compile-client

java.policy: FORCE
	@echo "Creating client java policy"
	@echo "grant codebase \"file:`pwd`/\" {" > java.policy
	@echo "permission java.security.AllPermission;" >> java.policy
	@echo "};" >> java.policy

FORCE: ;

../Server/RMIInterface.jar: ../Server/Server/Interface/*.java
	make -C ../Server/ RMIInterface.jar


compile-client: ../Server/RMIInterface.jar
	javac -cp .:../Server/RMIInterface.jar Client/*.java

bundle-client: compile-client
	jar cvf RMIClient.jar ./Client/$(wildcard *.class)

clean:
	rm -f Client/*.class
	rm -f ../Server/RMIInterface.jar
	rm -f java.policy
